server:
  port: 9002
spring:
  application:
    name: kangkang-store-service
  cloud:
    nacos:
      discovery:
        server-addr: 110.40.235.203:8848
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://110.40.235.203:3306/kangkang?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password: root123
  main:
    allow-bean-definition-overriding: true
  elasticsearch:
    rest:
      uris: http://101.43.21.125:9200
    jest:
      connection-timeout: 10
mybatis-plus:
  mapper-locations:
    - classpath*:/mapper/*.xml
  type-aliases-package: com.kangkang.store.entity   #在Mybatis的mapper.xml文件中resultType的type或者paramterType会返回自定义entity，此时可以用全类名名来指定这些实体

rocketmq:
  #mq的nameserver的地址
  namesrvAddr: 42.192.79.7:9876
  #生产者
  producer:
    #是否开启自动配置，是否将DefaultMQProducer，上面有个ConditionalOnProperty注解就是控制类是否注入spring容器
    isOnOff: on
    #发送同一类消息设置为同一个group，保证唯一默认不需要设置
    groupName: kangkang-store-service-produce
    #消息的最大长度，默认4M，也就是1024*4
    maxMessageSize: 4096
    #发送消息超市时间，默认为3000
    sendMsgTimeOut: 3000
    #消息发送失败重试次数，默认为2
    retryTimesWhenSendFailed: 2
jasypt:
  encryptor:
    password: a