#mybatis-plus.configuration.cache-enabled=true
#mybatis-plus.mapper-locations=classpath*:/mapper/*.xml
#mybatis-plus.type-aliases-package=com.sch.app.mybatis.entity
#logging.level.com.sch.app.mybatis.mapper= debug
server:
  port: 9002
spring:
  application:
    name: kangkang-store-service
  cloud:
    nacos:
      discovery:
        server-addr: 110.40.235.203:8848
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://110.40.235.203:3306/kangkang?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password: root123
  main:
    allow-bean-definition-overriding: true
mybatis-plus:
  mapper-locations:
    - classpath*:/mapper/*.xml
  type-aliases-package: com.kangkang.store.entity   #在Mybatis的mapper.xml文件中resultType的type或者paramterType会返回自定义entity，此时可以用全类名名来指定这些实体
