server:
  port: 10001
spring:
  application:
    name: kangkang-gateway
  cloud:
    gateway:
      discovery:
        locator:
          ####开启以服务id去注册中心上获取转发地址，也是开启网关服务注册和发现
          enabled: true
          lower-case-service-id: true   #将请求路径上的服务名配置为小写
      #路由策略
      routes:
        #路由id
        - id: store
          #转发地址：
          #          uri: http://localhost
          uri: lb://kangkang-store     #3、然后再去拼上转到该地址，或者服务。如果有后续的地址在在这里拼上资源路径
          #          uri: http://www.baidu.com/     #3、然后再去拼上转到该地址，或者服务。如果有后续的地址在在这里拼上资源路径
          #匹配规则  这是匹配url后面的路径，所有的请求都会先过网关
          predicates:
            - Path=/mini/store/**      #1、匹配规则，先通过断言进行匹配
          filters:
          #注意：下面的配置必须和filters齐平
          - StripPrefix=2       #2、然后过滤掉前两位
#          - name: RequestRateLimiter
#            args:
#              #replenishRate: 每次补充令牌数量
#              #burstCapacity: 令牌桶最大容量，突发请求数量
#              #requestedTokens: 每次请求消耗令牌的数量
#              #代表每秒限制请求一次
#              redis-rate-limiter.replenishRate: 1    #允许用户每秒处理多少个请求
#              redis-rate-limiter.burstCapacity: 1    #令牌桶的容量，允许在一秒内完成的最大的请求数量
#              redis-rate-limiter.requestedTokens: 1    #每次请求消耗令牌的数量
#              key-resolver: "#{@addHostKeyResolver}"  #使用什么方式的限流方式  这个是自己写的类  使用SpEL按名称引用bean

        #后台管理系统
        - id: manage
          uri: lb://manage-service
          predicates:
            - Path=/mini/manage/**
          filters:
            - StripPrefix=2

        #订单管理系统
        - id: order
          uri: lb://kangkang-order
          predicates:
            - Path=/mini/order/**
          filters:
            - StripPrefix=2       #2、然后过滤掉前两位

        #文件处理系统
        - id: file
          uri: lb://kangkang-file-process
          predicates:
            - Path=/mini/file/**
          filters:
            - StripPrefix=2       #2、然后过滤掉前两位

    nacos:
      discovery:
        server-addr: 110.40.235.203:8848
    sentinel:   #限流设置，如果需要，要在配置类中添加限流规则，要指定相应的服务，也就是上面的路由id
      transport:
#        dashboard: 110.40.235.203:8858
        #限流模式注册到sentinel控制台，在控制台可以部署一些规则
        dashboard: 127.0.0.1:8080
        port: 8719
        #服务启动直接建立心跳连接
      eager: true
  redis:
    host: 110.40.235.203   #主机
    port: 6379          #端口
    password: promise123   #密码
    jedis:              #注意这里要设置最大活跃线程要通过jedis
      pool:
        max-active: 200   # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1      #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10      #连接池中的最大空闲连接
        min-idle: 0       #连接池中的最小空闲连接
    timeout: 1000         #连接超时时间（毫秒）
  main:
    allow-bean-definition-overriding: true
wx:
  open:
    app_id: wxedb4d43b2e668dce
    app_secret: 1fddc8f2e431815be10d1134e33fbb64
    redirect_url: https://api.weixin.qq.com/sns/jscode2session
  sch:
   timeout: 72    #token的过期时间,时间单位为小时
jasypt:
  encryptor:
    password: gatawey