server:
  port: 10001
spring:
  application:
    name: kangkang-gateway
  cloud:
    gateway:
      discovery:
        locator:
          ####开启以服务id去注册中心上获取转发地址，也是开启网关服务注册和发现
          enabled: true
          lower-case-service-id: true   #将请求路径上的服务名配置为小写
      #路由策略
      routes:
        #路由id
        - id: kkstore
          #转发地址：
#          uri: http://localhost
          uri: lb://kangkang-store     #3、然后再去拼上转到该地址，或者服务。如果有后续的地址在在这里拼上资源路径
#          uri: http://www.baidu.com/     #3、然后再去拼上转到该地址，或者服务。如果有后续的地址在在这里拼上资源路径
          #匹配规则  这是匹配url后面的路径，所有的请求都会先过网关
          predicates:
            - Path=/kk/**      #1、匹配规则，先通过断言进行匹配
          filters:
            - StripPrefix=1       #2、然后过滤调第一位
    nacos:
      discovery:
        server-addr: 10.211.55.9:8848
    sentinel:   #限流设置，如果需要，要在配置类中添加限流规则，要指定相应的服务，也就是上面的路由id
      transport:
        dashboard: 10.211.55.9:8858
  redis:
    host: 10.211.55.9   #主机
    port: 6379          #端口
    password: root123   #密码
    jedis:              #注意这里要设置最大活跃线程要通过jedis
      pool:
        max-active: 200   # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1      #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10      #连接池中的最大空闲连接
        min-idle: 0       #连接池中的最小空闲连接
    timeout: 1000         #连接超时时间（毫秒）
wx:
  open:
    app_id: wxedb4d43b2e668dce
    app_secret: 1fddc8f2e431815be10d1134e33fbb64
    redirect_url: https://api.weixin.qq.com/sns/jscode2session
redis:
   timeout: 72    #token的过期时间,时间单位为小时