server:
  port: 8083
spring:
  application:
    name: kangkang-order
  cloud:
    nacos:
      discovery:
        server-addr: 110.40.235.203:8848
  logging:
    level:
      root: info
  #logging.level.org.springframework=info
logging:
  level:
    org:
    springframework: info


#这里是配置文件的方式配置策略
kangkang-order-service:
  ribbon:

    #    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule #配置规则 随机
    #    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RoundRobinRule #配置规则 轮询
    #    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RetryRule #配置规则 重试
    #    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.WeightedResponseTimeRule #配置规则 响应时间权重
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.BestAvailableRule #配置规则 最空闲连接策略
    ConnectTimeout: 5000 #请求连接超时时间
    ReadTimeout: 1000 #请求处理的超时时间
    OkToRetryOnAllOperations: true #对所有请求都进行重试
    MaxAutoRetriesNextServer: 2 #切换实例的重试次数
    MaxAutoRetries: 1 #对当前实例的重试次数
#
#ribbon:
#  #指的是建立连接所用的时间，适用于网络状况正常的情况下，两端连接所用的时间
#  ReadTimeout: 50000
#  #指的是建立连接后从服务器读取到可用资源所用的时间
#  ConnectTimeout: 50000

#  logstash:
#    server: 101.43.21.125
#      port: 9601
#ribbon:
#
#    #    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule #配置规则 随机
#    #    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RoundRobinRule #配置规则 轮询
#    #    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RetryRule #配置规则 重试
#    #    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.WeightedResponseTimeRule #配置规则 响应时间权重
#  NFLoadBalancerRuleClassName: com.netflix.loadbalancer.BestAvailableRule #配置规则 最空闲连接策略
#  ConnectTimeout: 500 #请求连接超时时间
#  ReadTimeout: 1000 #请求处理的超时时间
#  OkToRetryOnAllOperations: true #对所有请求都进行重试
#  MaxAutoRetriesNextServer: 2 #切换实例的重试次数
#  MaxAutoRetries: 1 #对当前实例的重试次数