server:
  port: 8083
spring:
  application:
    name: kangkang-order
  cloud:
    nacos:
      discovery:
        server-addr: 110.40.235.203:8848
  logging:
    level:
      root: info
  #logging.level.org.springframework=info
logging:
  level:
    org:
    springframework: info
