#mybatis-plus.configuration.cache-enabled=true
#mybatis-plus.mapper-locations=classpath*:/mapper/*.xml
#mybatis-plus.type-aliases-package=com.sch.app.mybatis.entity
#注意，下面的redis和datasorce是有顺序的，不然系统启动不起来。先redis，然后在datasource，然后在其他的
server:
  port: 9003
spring:
  application:
    name: kangkang-order-service
  cloud:
    nacos:
      discovery:
        server-addr: 110.40.235.203:8848
  redis:
    host: 110.40.235.203   #主机
    port: 6379          #端口
    password: promise123   #密码
    jedis:              #注意这里要设置最大活跃线程要通过jedis
      pool:
        max-active: 200   # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1      #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10      #连接池中的最大空闲连接
        min-idle: 0       #连接池中的最小空闲连接
    timeout: 1000         #连接超时时间（毫秒）
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://110.40.235.203:3306/kangkang?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password: root123
  main:
    allow-bean-definition-overriding: true
#rocketmq的配置信息
mybatis-plus:
  mapper-locations:
    - classpath*:/mapper/*.xml
  type-aliases-package: com.kangkang.store.entity   #在Mybatis的mapper.xml文件中resultType的type或者paramterType会返回自定义entity，此时可以用全类名名来指定这些实体


#日志配置
#logging:
#  config: classpath:logback.xml
ribbon:
  #指的是建立连接所用的时间，适用于网络状况正常的情况下，两端连接所用的时间
  ReadTimeout: 50000
  #指的是建立连接后从服务器读取到可用资源所用的时间
  ConnectTimeout: 50000
logging:
  level:
    com.kangkang.dao: debug
