server:
  port: 9001
spring:
  application:
    name: kangkang-manage
  cloud:
    nacos:
      discovery:
        server-addr: 110.40.235.203:8848
  redis:
    host: 110.40.235.203   #主机
    port: 6379          #端口
    password: promise123   #密码
    jedis: #注意这里要设置最大活跃线程要通过jedis
      pool:
        max-active: 200   # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1      #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10      #连接池中的最大空闲连接
        min-idle: 0       #连接池中的最小空闲连接
    timeout: 1000         #连接超时时间（毫秒）
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://110.40.235.203:3306/kangkang?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password: root123
  main:
    allow-bean-definition-overriding: true #spring Could 允许单个服务消费者被多次服务
#ribbon:
#  restclient:
#    enabled: true
mybatis-plus:
  mapper-locations:
    - classpath*:/mapper/*.xml
  type-aliases-package: com.kangkang.manage.entity
#rocketmq的配置信息
rocketmq:
  #消费者
  consumer:
    namesrvAddr: 124.222.55.62:9876
    #是否开启自动配置
    isOnOff: on
    #发送同一类消息设置为同一个group，保证唯一默认不需要设置
    groupName: kangkang-manage-consumer
    #消费者线程数
    consumeThreadMin: 5
    consumeThreadMax: 32
    #设置一次消费信心的条数  默认为1
    consumeMessageBatchMaxSize: 1

