server:
  port: 8085
spring:
  application:
    name: kangkang-log
  cloud:
    nacos:
      discovery:
        server-addr: 110.40.235.203:8848
  logging:
    level:
      root: info
  #logging.level.org.springframework=info
  elasticsearch:
    rest:
      uris: http://101.43.21.125:9200
    jest:
      connection-timeout: 10
logging:
  level:
    org:
    springframework: info
ribbon:
  #指的是建立连接所用的时间，适用于网络状况正常的情况下，两端连接所用的时间
  ReadTimeout: 50000
  #指的是建立连接后从服务器读取到可用资源所用的时间
  ConnectTimeout: 50000

#  logstash:
#    server: 101.43.21.125
#      port: 9601
