server:
  port: 8084
spring:
  application:
    name: kangkang-file-process
  cloud:
    nacos:
      discovery:
        server-addr: 110.40.235.203:8848
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://110.40.235.203:3306/kangkang?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password: root123
  logging:
    level:
      root: info
  #logging.level.org.springframework=info
  elasticsearch:
    rest:
      uris: http://101.43.21.125:9200
    jest:
      connection-timeout: 10
ribbon:
  #指的是建立连接所用的时间，适用于网络状况正常的情况下，两端连接所用的时间
  ReadTimeout: 50000
  #指的是建立连接后从服务器读取到可用资源所用的时间
  ConnectTimeout: 50000
mybatis-plus:
  mapper-locations:
    - classpath*:/mapper/*.xml


file:
  hostname: 124.222.55.62
  username: sch
  password: sch1234
  commentPath: /home/sch/media/comment

rocketmq:
  #消费者
  consumer:
    namesrvAddr: 124.222.55.62:9876

    #是否开启自动配置
    isOnOff: on
    #发送同一类消息设置为同一个group，保证唯一默认不需要设置
    groupName: kangkang-fileprocess-consumer
    #消费者线程数，根据实际业务来，如果有阻塞可以适当的放大些
    consumeThreadMin: 5
    consumeThreadMax: 32
    #设置一次消费信心的条数  默认为1
    consumeMessageBatchMaxSize: 1